# -*- coding: utf-8 -*-
"""Email_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_S8nTSJN1jeYhAfGbITUZWRp5ME9jfP
"""

# import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import  LogisticRegression
from sklearn.metrics import accuracy_score

# making a dataframe
df = pd.read_csv('mail_data.csv')
# checking no. of rows and columns in the data frame
df.shape

df.head() # printing first 5 rows

df.info()

# checking for any null values
df.isnull().sum()

df.sample(5)

"""Label Encoding"""

# labeling spam as 1 and ham as 0
from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()
df['Category'] = Encoder.fit_transform(df['Category'])

df.head()

# assigning axes to the categories
X = df['Message']
Y = df['Category']
X

Y

"""Training data and testing data split"""

# splitting data into 80% for training and 20% for testing
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 3)
print(X.shape)
print(X_train.shape)
print(X_test.shape)

"""Feature Extraction"""

# transforming the text data to feature vectors -> logistic regression
fexet = TfidfVectorizer(min_df = 1, stop_words='english', lowercase = True)
X_train_features = fexet.fit_transform(X_train)
X_test_features = fexet.transform(X_test)

print(X_train_features)

print(X_train)
print(X_test_features)

# creating model
model = LogisticRegression()

model.fit(X_train_features, Y_train)

# prediction on training data
prediction = model.predict(X_train_features)
accuracy = accuracy_score(Y_train, prediction)

print(f"Accuracy on training data: {accuracy*100} %")

# prediction on test data
prediction_test = model.predict(X_test_features)
accuracy_test = accuracy_score(Y_test, prediction_test)

print(f"Accuracy on testing data: {accuracy_test*100} %")

input_mail = ["Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?"]

#convet text to feature vectors
input_data_features = fexet.transform(input_mail)

#making pedictions
prediction = model.predict(input_data_features)
print(prediction)

model.fit(X_train_features, Y_train)

model.fit(X_train_features, Y_train)

# splitting data into 80% for training and 20% for testing
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 3)
print(X.shape)
print(X_train.shape)
print(X_test.shape)

# transforming the text data to feature vectors -> logistic regression
fexet = TfidfVectorizer(min_df = 1, stop_words='english', lowercase = True)
X_train_features = fexet.fit_transform(X_train)
X_test_features = fexet.transform(X_test)

# Y_train and Y_test are already integers from the LabelEncoder, no further mapping is needed here.
# The previous mapping to {'ham': 0, 'spam': 1} resulted in NaNs because the values were already 0s and 1s.

print(X_train_features)

"""Evaluating the trained model"""

# prediction on training data
prediction = model.predict(X_train_features)
accuracy = accuracy_score(Y_train, prediction)

print(f"Accuracy on training data: {accuracy*100} %" )

# prediction on test data
prediction_test = model.predict(X_test_features)
accuracy_test = accuracy_score(Y_test, prediction_test)

print(f"Accuracy on testing data: {accuracy_test*100} %" )

"""Creating a Predicting model"""

input_mail = ["Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?"]

#convet text to feature vectors
input_data_features = fexet.transform(input_mail)

#making pedictions
prediction = model.predict(input_data_features)
print(prediction)

import pickle
pickle.dump(fexet, open('vectorizer.pkl', 'wb'))
pickle.dump(model, open('model.pkl', 'wb'))

